import {
  BaggageClaimIcon,
  BookOpenIcon,
  BriefcaseBusinessIcon,
  CarFrontIcon,
  DumbbellIcon,
  GiftIcon,
  HeartPulseIcon,
  HouseIcon,
  MailboxIcon,
  PawPrintIcon,
  PiggyBankIcon,
  ReceiptTextIcon,
  ShoppingCartIcon,
  TicketIcon,
  ToolCaseIcon,
  UtensilsIcon,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  briefcase: BriefcaseBusinessIcon,
  car: CarFrontIcon,
  heartPulse: HeartPulseIcon,
  piggyBank: PiggyBankIcon,
  shoppingCart: ShoppingCartIcon,
  ticket: TicketIcon,
  toolCase: ToolCaseIcon,
  utensils: UtensilsIcon,
  pawPrint: PawPrintIcon,
  house: HouseIcon,
  gift: GiftIcon,
  dumbbell: DumbbellIcon,
  bookOpen: BookOpenIcon,
  baggageClaim: BaggageClaimIcon,
  mailbox: MailboxIcon,
  receiptText: ReceiptTextIcon,
};